import type { components, paths } from "./generated/api-schema";

type SchemaName = keyof components["schemas"];
type Schema<K extends SchemaName> = components["schemas"][K];

export type ApiPaths = paths;
export type ApiSchemas = components["schemas"];

export type FillProfile = Schema<"FillProfileOut">;
export type SubstrateRecipeVersion = Schema<"SubstrateRecipeVersionOut">;
export type SpawnRecipe = Schema<"SpawnRecipeOut">;
export type MixLot = Schema<"MixLotOut">;
export type MushroomSpecies = Schema<"MushroomSpeciesOut">;
export type LiquidCulture = Schema<"LiquidCultureOut">;
export type GrainType = Schema<"GrainTypeOut">;
export type Ingredient = Schema<"IngredientOut">;
export type IngredientLot = Schema<"IngredientLotOut">;
export type PasteurizationRun = Schema<"PasteurizationRunOut">;
export type SterilizationRun = Schema<"SterilizationRunOut">;
export type Bag = Schema<"BagOut">;
export type BagStatusEvent = Schema<"BagStatusEventOut">;
export type LineageChildBag = Schema<"LineageChildBagOut">;
export type BagCollectionSummary = Schema<"BagCollectionSummaryOut">;
export type BagDetail = Schema<"BagDetailOut">;
export type Inoculation = Schema<"InoculationOut">;
export type HarvestEvent = Schema<"HarvestEventOut">;
export type ReportGroup = Schema<"ReportGroupOut">;
export type PasteurizationRunMetrics = Schema<"PasteurizationRunMetricsOut">;
export type SubstrateBagMetrics = Schema<"SubstrateBagMetricsOut">;
export type ContaminationCase = Schema<"ContaminationCaseOut">;
export type DataQualityIssue = Schema<"DataQualityIssueOut">;
export type ProductionReportSummary = Schema<"ProductionReportSummaryOut">;
export type ProductionReport = Schema<"ProductionReportOut">;
export type DashboardQueue = Schema<"DashboardQueueOut">;
export type DashboardRunSummary = Schema<"DashboardRunSummaryOut">;
export type DashboardActivity = Schema<"DashboardActivityOut">;
export type DashboardAlert = Schema<"DashboardAlertOut">;
export type DashboardOverview = Schema<"DashboardOverviewOut">;
export type SterilizationRunDetail = Schema<"SterilizationRunDetailOut">;
export type PasteurizationRunDetail = Schema<"PasteurizationRunDetailOut">;
